server:
  port: 8084

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgress
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT Configuration
jwt:
  secret: YourSecretKeyMustBeAtLeast32CharactersLong!
  expiration: 3600000
