server:
  port: 8081

spring:
  application:
    name: order-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orders}
    username: postgress
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Zipkin
spring.zipkin.base-url: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411}

spring.sleuth.sampler.probability: 1.0
