server:
  port: 8081

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgress
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092

# Zipkin
spring.zipkin.base-url: http://localhost:9411

spring.sleuth.sampler.probability: 1.0
